version: 2
jobs:
    build-and-test-gunzip:
        docker:
            - image: circleci/node:8.12.0
        working_directory: ~/gunzip
        steps:
            - checkout
            - restore_cache:
                name: Restore node_modules from cache
                keys:
                  - v2-npm-deps-{{ checksum "package.json" }}
            - run:
                name: Install Node.js dependencies
                command: npm i
            - save_cache:
                name: Save node_modules to cache
                key: v2-npm-deps-{{ checksum "package.json" }}
                paths:
                  - node_modules
            - run:
                name: Run the tests!
                command: npm test
            - persist_to_workspace:
                root: ~/gunzip
                paths:
                  - ./

    publish-to-npm:
      docker:
          - image: circleci/node:8.12.0
      steps:
          - attach_workspace:
              at: ~/gunzip
          - run:
              name: Publish to npm registry
              command: |
                cd ~/gunzip
                echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
                npm publish


workflows:
    version: 2
    test-and-publish-gunzip:
        jobs:
            - build-and-test-gunzip
            - publish-to-npm:
                requires:
                  - build-and-test-gunzip
                filters:
                  tags:
                    only: /v[0-9].[0-9].[0.9]/
                  branches:
                    only: master